# Generated by Django 5.0.6 on 2024-07-16 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_publication'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=25)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('comment', models.TextField(max_length=500)),
                ('avatar', models.ImageField(upload_to='')),
                ('create_date', models.DateField(null=True)),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='MokkoContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Контакты Мокко',
                'verbose_name_plural': 'Контакты Мокко',
            },
        ),
        migrations.AlterModelOptions(
            name='coffees',
            options={'verbose_name': 'Кофе', 'verbose_name_plural': 'Кофе'},
        ),
        migrations.AlterModelOptions(
            name='publication',
            options={'verbose_name': 'Публикация', 'verbose_name_plural': 'Публикации'},
        ),
    ]
