# Generated by Django 5.0.6 on 2024-07-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_clientcontact_feedback_mokkocontact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NameVerbose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titlle', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='clientcontact',
            options={'verbose_name': 'Клиент Контакты', 'verbose_name_plural': 'Клиент Контакты'},
        ),
    ]
