# Generated by Django 5.0.6 on 2024-07-16 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_nameverbose_alter_clientcontact_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nameverbose',
            options={'verbose_name': 'Названия', 'verbose_name_plural': 'Названия'},
        ),
    ]
