# Generated by Django 5.0.6 on 2024-07-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_nameverbose_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='mokkocontact',
            name='short_description',
            field=models.TextField(null=True),
        ),
    ]
